# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# netCDFToChlor1.py
# Created on: 2020-04-23 11:37:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
import arcpy.da
from arcpy.sa import *
from arcpy.md import *

arcpy.CheckOutExtension("Spatial")
arcpy.env.overwriteOutput = True
arcpy.env.workspace = r"T:\Students\reid98\Final Project\Data4.gdb"
os.chdir(r"T:\Students\reid98\Final Project\Leftover Data")
ncDir = r"T:\Students\reid98\Final Project\Leftover Data\\"

# Local variables:
lake_superior_basin = r"T:\Students\reid98\Final Project\reid\lake_superior_simple.shp"

# Process: Make NetCDF Raster Layer
rasterList = [raster for raster in os.listdir(".") if raster[-2:]=="nc"]
for raster in rasterList:
    name = raster[:15]
    print name
    print ncDir+raster
    arcpy.MakeNetCDFRasterLayer_md(ncDir+raster, "chlor_a", "lon", "lat", name, "", "", "BY_VALUE")


# Process: Zonal Statistics as Table
    arcpy.gp.ZonalStatisticsAsTable_sa(lake_superior_basin, "OID_", name, name+"_stats", "DATA", "ALL")

    # Adds a Text field called "date", and calculates the value to be the year and 3 digit day of the year of the start of the month
    # e.g. for A20022742002304, it will be 2002274.  Note that the date is represented as text- we can represent it as a number, if you want!
    
    arcpy.AddField_management(arcpy.env.workspace + "\\" + name+"_stats", "date", "TEXT", "","","10","", "NULLABLE","NON_REQUIRED","")
    arcpy.CalculateField_management(arcpy.env.workspace + "\\" + name+"_stats", "date", "\"" + str(name[1:8])+"\"", "PYTHON","") 
    print "success"
